# Generated by Django 5.2.6 on 2025-09-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(default='patient', max_length=20)),
                ('photo', models.ImageField(default='', upload_to='user_photo')),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
