# Generated by Django 5.2.6 on 2025-09-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pemail', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(choices=[('diagnostic', 'diagnostic'), ('psychological', 'psychological'), ('therapy', 'therapy'), ('counseling', 'counseling')], max_length=52)),
                ('pphone', models.BigIntegerField()),
                ('date', models.DateField()),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
