# Generated by Django 5.2.6 on 2025-09-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pemail',
            field=models.EmailField(max_length=254),
        ),
    ]
