# Generated by Django 5.2.6 on 2025-09-29 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'patient'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='myapp.user'),
        ),
    ]
